stages:
  - distribute

Azure branch:
  stage: distribute
  image: mcr.microsoft.com/azure-cli

  tags:
    - docker
    - amd64

  only:
    - production
    - main

  script:
    - yum update -y
    - yum install tar xz -y
    - echo ${CI_COMMIT_BRANCH}
    - tar cf /tmp/teskalabs-versions-library.tar --exclude='.git'  --exclude='./.git' --exclude='./.gitignore' --exclude='./.gitlab-ci.yml' --exclude='./README.md' --exclude='./CHANGELOG' --exclude='./CONTRIBUTING.md' --exclude='./LICENSE' .
    - xz -9 -e -T 0 /tmp/teskalabs-versions-library.tar
    - ls /tmp
    - mv /tmp/teskalabs-versions-library.tar.xz teskalabs-versions-library-${CI_COMMIT_BRANCH}.tar.xz
    # Calculate the checksum
    - sha256sum teskalabs-versions-library-${CI_COMMIT_BRANCH}.tar.xz > teskalabs-versions-library-${CI_COMMIT_BRANCH}.tar.xz.sha256
    
    - az storage blob upload --overwrite --file teskalabs-versions-library-${CI_COMMIT_BRANCH}.tar.xz --container-name "\$web" --name "teskalabs-versions-library/teskalabs-versions-library-${CI_COMMIT_BRANCH}.tar.xz" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
    - az storage blob upload --overwrite --file teskalabs-versions-library-${CI_COMMIT_BRANCH}.tar.xz.sha256 --container-name "\$web" --name "teskalabs-versions-library/teskalabs-versions-library-${CI_COMMIT_BRANCH}.tar.xz.sha256" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"

  artifacts:
    paths:
      - teskalabs-versions-library-${CI_COMMIT_BRANCH}.tar.xz
      - teskalabs-versions-library-${CI_COMMIT_BRANCH}.tar.xz.sha256

Azure tag:
  stage: distribute
  image: mcr.microsoft.com/azure-cli

  tags:
    - docker
    - amd64

  only:
    - tags
  except:
    - branches

  script:
    - yum update -y
    - yum install tar xz -y
    - echo ${CI_COMMIT_REF_NAME}
    - tar cf /tmp/teskalabs-versions-library.tar --exclude='.git'  --exclude='./.git' --exclude='./.gitignore' --exclude='./.gitlab-ci.yml' --exclude='./README.md' --exclude='./CHANGELOG' --exclude='./CONTRIBUTING.md' --exclude='./LICENSE' .
    - xz -9 -e -T 0 /tmp/teskalabs-versions-library.tar
    - ls /tmp
    - mv /tmp/teskalabs-versions-library.tar.xz teskalabs-versions-library-${CI_COMMIT_REF_NAME}.tar.xz
    # Calculate the checksum
    - sha256sum teskalabs-versions-library-${CI_COMMIT_REF_NAME}.tar.xz > teskalabs-versions-library-${CI_COMMIT_REF_NAME}.tar.xz.sha256
    
    - az storage blob upload --overwrite --file teskalabs-versions-library-${CI_COMMIT_REF_NAME}.tar.xz --container-name "\$web" --name "teskalabs-versions-library/teskalabs-versions-library-${CI_COMMIT_REF_NAME}.tar.xz" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
    - az storage blob upload --overwrite --file teskalabs-versions-library-${CI_COMMIT_REF_NAME}.tar.xz.sha256 --container-name "\$web" --name "teskalabs-versions-library/teskalabs-versions-library-${CI_COMMIT_REF_NAME}.tar.xz.sha256" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"

  artifacts:
    paths:
      - teskalabs-versions-library-${CI_COMMIT_REF_NAME}.tar.xz
      - teskalabs-versions-library-${CI_COMMIT_REF_NAME}.tar.xz.sha256
